# Spring Application Settings
spring.application.name=book-review-svc
server.servlet.context-path=/
server.port=8080

# Logging Configuration
logging.level.root=INFO
logging.level.com.epam.book_review_svc=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

# Springdoc OpenAPI (Swagger) Configuration
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs

# Data Storage Configuration
app.data.file.location=classpath:data/books.json
app.data.file.encoding=UTF-8
